# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
  

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: y4t0
      
title: Welcome to my page!
description: >- # this means to ignore newlines until "baseurl:"
  Only after disaster can we be resurrected
baseurl: "/wabi-sabi" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: yunaranyancat
#github_username:  yunaranyancat
error_message: >-
  Whoops! You have reached the no man's land...
# github:
#   repository_url: http://www.google.com
